substitutions:
  project_ver_let: u


packages:
  kauf_rgbsw_base:
    url: https://github.com/KaufHA/kauf-rgb-switch
    files: kauf-rgbs.yaml
    refresh: 0s


dashboard_import:
  package_import_url: github://KaufHA/kauf-rgb-switch/kauf-rgbs.yaml


esphome:
  name_add_mac_suffix: true


# re-adding wifi component so that hotspot will be enabled
wifi:

  # enable wifi ap, which was not needed in dashboard import version
  ap:
    ssid: ${friendly_name} Hotspot
    ap_timeout: 2147483647ms      # maximum 32 bit value.  About 3.5 weeks in milliseconds.

  # by default, fast_connect is disabled.  Will automatically be enabled by wifi component
  # needs to be set false here as dashboard import version sets true
  fast_connect: false
  
  # add forced hash which isn't needed for dashboard import.  Allows saving wifi credentials across update.
  forced_hash: 2179908191


captive_portal:


button:
  - platform: template
    id: clear_wifi_button
    name: $friendly_name Clear Wifi Credentials
    entity_category: diagnostic
    disabled_by_default: $disable_entities
    on_press:
      then:
      - lambda: wifi_wificomponent->clear_stored_creds();
      - delay: 2s
      - button.press: restart_button  