substitutions:
  project_ver_let: u
  wifi_ap_timeout: 15s


packages:
  kauf_rgbsw_base:
    url: https://github.com/KaufHA/kauf-rgb-switch
    files: kauf-rgbs.yaml
    refresh: 0s


dashboard_import:
  package_import_url: github://KaufHA/kauf-rgb-switch/kauf-rgbs.yaml


esphome:
  name_add_mac_suffix: true


# re-adding wifi component so that hotspot will be enabled
wifi:

  # by default, fast_connect is disabled.  Will automatically be enabled by wifi component
  # needs to be set false here to overwrite dashboard import version setting true
  fast_connect: false

  # add forced hash which isn't needed for dashboard import.  Allows saving wifi credentials across update.
  forced_hash: 2179908191
