substitutions:
  name: rgbsw-dev
  friendly_name: RGB Sw Dev

  wifi_ap_timeout: 15s
  disable_entities: 'false'
  sub_wifi_reset_script: script_do_nothing

# external_components:
#   - source:
#       type: git
#       url: https://github.com/KaufHA/common
#       ref: v2023.03.14
#     refresh: always

external_components:
  - source:
      type: local
      path: ../common/components


packages:
  # kauf.rgbs: !include kauf-rgbs-4m.yaml
  kauf.rgbs: !include kauf-rgbs.yaml

#  rotate.git:    github://KaufHA/kauf-rgb-switch/yaml-features/rotate-colors-sync-to-ha-light.yaml
#  rotate.local: !include yaml-features/rotate-colors-sync-to-ha-light.yaml

#  fan.local: !include yaml-features/hold-for-fan-mode.yaml
#  fan.git:   github://KaufHA/kauf-rgb-switch/yaml-features/hold-for-fan-mode.yaml

#  kauf.rgbs: github://KaufHA/kauf-rgb-switch/kauf-rgbs.yaml

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

#   manual_ip:
#     static_ip: !secret hall_switch_n1_ip_address
#     gateway: !secret wifi_gateway
#     subnet: !secret wifi_subnet
#     dns1: !secret wifi_dns1

  #use_address: 192.168.86.213

