esphome_pass: lk1zLWchfxKm

# Your Wi-Fi SSID and password
wifi_ssid: "noagendashow.com"
wifi_password: "dfaceandthekauf"















# ip addresses, in secrets so there is one place to reference static ips.
wifi_gateway:                         192.168.86.1
wifi_subnet:                          255.255.254.0
wifi_dns1:                            192.168.86.71


####################################################
garage_meter_ip_address:              192.168.87.100
bedroom_box_fan_ip_address:           192.168.87.101
garage_light_ip_address:              192.168.87.102
garage_door_ip_address:               192.168.87.103
hall_switch_f_ip_address:             192.168.87.104
hall_switch_s2_ip_address:            192.168.87.105
hall_switch_s1_ip_address:            192.168.87.106
kitchen_switches_ip_address:          192.168.87.107
bed_lamp_touch_1_ip_address:          192.168.87.108
bed_lamp_touch_2_ip_address:          192.168.87.109


####################################################
back_porch_north_ip_address:          192.168.87.110
hall_switch_n2_ip_address:            192.168.87.111
bedroom_light_ip_address:             192.168.87.112
monitor_backlight_ip_address:         192.168.87.113
hall_deco_bulb_ip_address:            192.168.87.114
hvac_relays_ip_address:               192.168.87.115
hall_switch_n1_ip_address:            192.168.87.116

esphome_cord_1_ip_address:            192.168.87.118
kettle_ip_address:                    192.168.87.119


####################################################
back_porch_south_ip_address:          192.168.87.120
pantry_switch_ip_address:             192.168.87.121
pantry_bulb_ip_address:               192.168.87.122
doorbell_ip_address:                  192.168.87.123
bk_office_light_ip_address:           192.168.87.124
bistro_dimmer_ip_address:             192.168.87.125
hall_bulb_s_ip_address:               192.168.87.126
hall_bulb_f_ip_address:               192.168.87.127
hall_bulb_n1_ip_address:              192.168.87.128
hall_bulb_n2_ip_address:              192.168.87.129


####################################################
kitchen_bulb_10_ip_address:           192.168.87.130
kitchen_bulb_01_ip_address:           192.168.87.131
kitchen_bulb_02_ip_address:           192.168.87.132
kitchen_bulb_03_ip_address:           192.168.87.133
kitchen_bulb_04_ip_address:           192.168.87.134
kitchen_bulb_05_ip_address:           192.168.87.135
kitchen_bulb_06_ip_address:           192.168.87.136
kitchen_bulb_07_ip_address:           192.168.87.137
kitchen_bulb_08_ip_address:           192.168.87.138
kitchen_bulb_09_ip_address:           192.168.87.139


####################################################
kettle_screen_ip_address:             192.168.87.140
kauf_bulb_cw_ip_address:              192.168.87.141
kauf_bulb_cw2_ip_address:             192.168.87.142
hasp_ip_address:                      192.168.87.143

bnw_vent_ip_address:                  192.168.87.145


bedroom_lamp_1_ip_address:            192.168.87.148
bedroom_lamp_2_ip_address:            192.168.87.149


####################################################
christmas_tree_ip_address:            192.168.87.150
christmas_garland_ip_address:         192.168.87.151
christmas_lights_1_ip_address:        192.168.87.152
christmas_lights_2_ip_address:        192.168.87.153
